miNombre = "Hugo";
miApellido = "Romero";
estudiante = miNombre + " " + miApellido;
estudianteMayus = estudiante.toUpperCase();
estudianteMinus = estudiante.toLowerCase();
estudianteLen = estudiante.length;
estudianteFirst = miNombre.charAt();
estudianteEnd = miApellido.charAt(miApellido.length - 1);
estudianteSin = estudiante.replace(/ /g, "");
